language: python

services:
  - docker

before_install:
- docker pull carlad/sinatra
- docker run -p 80:80 ciilie/helloworld:rest-api
- docker ps -a

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
- python client.py
