language: python

services:
  - docker

before_install:
- docker pull carlad/sinatra
- docker run -p 80:80 ciilie/helloworld:rest-api
- docker ps -a
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
- python client.py
