language: python

services:
  - docker

before_install:
- docker pull ciilie/helloworld
- docker run -d -p 80:80 ciilie/helloworld:rest-api
- docker ps -a

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
- python client.py
